### ISSUE TITLE
More detailed error log on schema error

### ISSUE THREAD

**Issue by michal-harish** [amient/affinity#225]

**Comment by fbonazza** [comment]
in this line if (j.has("error_code")) throw new RuntimeException(subject + ": " + schema.getFullName + " - " + j.get("message").getTextValue) in ConfluentSchemaRegistry, can you log the entire schema?

This is because when we get an incompatible schema error, considering that Affinity favors the usage of case classes, you can query the versions of the schema from the registry but there's no way to get the schema which an application is trying to publish (and failing to)

also, it seems getFullName is null in this specific case, does that hint you anything or is that true for all the case classes
